### ISSUE TITLE
The creation process page, after start, only erased the disk, could not copy install... app to USB stick.

### ISSUE THREAD

**Issue by DevLiuSir** [MacThings/anymacos#2]
**After erasing the disk, there is no progress. Unable to copy to USB stick ？**

<img width="867" alt="截屏2023-02-07 16 09 39" src="https://user-images.githubusercontent.com/11488337/217188381-dbf7fe09-c9e3-40bb-8006-1a157b61ab64.png">
<img width="818" alt="截屏2023-02-07 16 09 52" src="https://user-images.githubusercontent.com/11488337/217188392-dbf554d5-945a-42fd-856c-e478c10bdeaa.png">
<img width="744" alt="截屏2023-02-07 16 10 00" src="https://user-images.githubusercontent.com/11488337/217188408-ab83a29d-1380-4c3f-a4a8-a00aed8ee5c9.png">

**Comment by MacThings** [comment]
It seems you have any Anti-Malware Software running? I don´t  know from 
which Application these Fingerprint Icon is. Seems to be a "false 
alert". What means the Text in the Popup in English?

-------- Originalnachricht --------

  		BETREFF:
  		[MacThings/anymacos] The creation process page, after start, only 
erased the disk, could not copy install... app to USB stick. (Issue #2)

  		DATUM:
  		2023-02-07 09:15

  		VON:
  		Marvin ***@***.***>

  		AN:
  		MacThings/anymacos ***@***.***>

After erasing the disk, there is no progress. Unable to copy to USB 
stick ？

  [1]

  [2]

  [3]

--
Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
You are receiving this because you are subscribed to this thread.Message 
ID: ***@***.***>

Links:
------
[1] 
https://user-images.githubusercontent.com/11488337/217188381-dbf7fe09-c9e3-40bb-8006-1a157b61ab64.png
[2] 
https://user-images.githubusercontent.com/11488337/217188392-dbf554d5-945a-42fd-856c-e478c10bdeaa.png
[3] 
https://user-images.githubusercontent.com/11488337/217188408-ab83a29d-1380-4c3f-a4a8-a00aed8ee5c9.png
[4] https://github.com/MacThings/anymacos/issues/2
[5]

**Comment by DevLiuSir** [comment]
The pop-up window is to get the root password. My MacBook is m1Max.

I think the scripting method "osascript-e 'do shell script 'sudo'" in "_Start_installer_creation()" didn't work.

**Comment by MacThings** [comment]
I think its a SIP Problem. There is nothing i can do. Only way is to disable SIP. Thanks to Apple. /-:

**Comment by DevLiuSir** [comment]
> I think its a SIP Problem. There is nothing i can do. Only way is to disable SIP. Thanks to Apple. /-:


Sure enough, it is enough to turn off SIP. thank you。

**Comment by DevLiuSir** [comment]
New issue: Unable to close the process of Activity Monitor. And the app is unresponsive！


<img width="746" alt="截屏2023-02-10 14 49 30" src="https://user-images.githubusercontent.com/11488337/218023068-24309834-30b4-4628-a877-cf7764106b0d.png">
